### ISSUE TITLE
Google authentication not working

### ISSUE THREAD

**Issue by brenopoggiali** [mattbutton/google-authentication-with-python-and-flask#1]
While testing this repository, I saw that, when you try to login, it gets stuck on `oauth2_tokens = session.fetch_access_token( ... )` (line 89 of google_auth.py). So we can never login. Is it possible to fix this?

**Comment by mattbutton** [comment]
Hi Breno - I've tested the code in this repo but am not able to reproduce the issue.

Did you manage to solve the issue? Any idea why it might be getting stuck on line 89?

**Comment by brenopoggiali** [comment]
Actually, I tried here again and it worked just fine. Thanks for your help and sorry for taking your time.
I believe this happened due to some instability in the Google token link. Before I open this issue, your repo was running smoothly as well.

Thanks for the reply and have a nice one!
